### ISSUE TITLE
snakemake: HTML report operational option

### ISSUE THREAD

**Issue by mvidalgarcia** [reanahub/reana-commons#288]
Depends on https://github.com/reanahub/reana-commons/issues/284

Introduce a Snakemake [operational option](http://docs.reana.io/reference/reana-yaml/#reanayaml-inputs) to enable the generation of [HTML reports](https://snakemake.readthedocs.io/en/stable/snakefiles/reporting.html).

```yaml
...
inputs:
  files:
    - code/helloworld.py
    - data/names.txt
  directories:
    - workflow/snakemake
  parameters:
    input: workflow/snakemake/inputs.yaml
  options:
    report: myreport.html
...
```
